server:
  port: 80

spring:
  application:
    name: web
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/itpylon?characterEncoding=utf-8&useSSL=false
      username: root
      password: zhinengxigua
      driver-class-name: com.mysql.jdbc.Driver
